[package]
name = "rtable-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
aruminium   = { path = "../../../honeycrisp/aruminium" }
unimem      = { path = "../../../honeycrisp/unimem" }
acpu        = { path = "../../../honeycrisp/acpu" }
blake-bench = { path = "../blake-bench" }
blake2      = "0.10"

[[bin]]
name = "rtable-bench"
path = "src/main.rs"

[lib]
name = "rtable_bench"
path = "src/lib.rs"
